baseURL = 'https://blog.jinof.vercel.app'
languageCode = 'en-us'
title = "Jinof's Blog"
theme = "mytheme"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]

[taxonomies]
  tag = "tags"
  category = "categories"
